version: "3.7"

services: 
    elasticsearch:
        image: elasticsearch:7.13.1
        ports: 
            - 9200:9200
        environment: 
            discovery.type: single-node
            node.name: es01
            cluster.name: es-doker-cluster
        volumes:
            - data01:/data/elasticsearch
        networks: 
            - elastic


networks: 
    elastic:
        driver: bridge

volumes: 
    data01: